### ISSUE TITLE
Birth time accuracy

### ISSUE THREAD

**Issue by PowerUser64** [DrMaxNix/birthdaycountdown#3]
Since the time until the birthday is counted to the minute, it would make sense to add the option to enter a time of birth so the birthday counter is accurate to the time of birth. Maybe this is something worth implementing?

**Comment by DrMaxNix** [comment]
Originally this app was meant to count down the time you have left until becoming an adult (in Germany, where I live, this is at the age of 18). And since you are legally an adult at 00:00 on that day it counts down to that time..
So counting down to the time you were born would be a completely other thing.. But I'll think about it..
If you have any idea how to implement it in a way that both of these ideas can coexist, let me know!

**Comment by DrMaxNix** [comment]
Could you tell me an example for a use case where you'd want to count down to the exact time of birth?

**Comment by PowerUser64** [comment]
Oh, sorry! I thought I responded to this. I was thinking if you wanted it to count down to 12:00 AM as the birth time, you could just tell it you were born at 12:00 AM. Maybe that's a bit simplistic of a solution, but it's the easiest one I could think of. You could even label it as "Time to count down to" rather than "Birth time" if you want. As for a use case, it's just another way to provide the user with accurate and fun information.
